spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_persons
    username: postgres
    password: Ichbin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    show-sql: true
